#URL to scrape tires from.
BASE_URL_123 = "https://padangos123.lt/"


# Tires dimensions to scrape.
DIMENSION = "245-45-R18"


FILTER_PARAMS = {
    "dimension": DIMENSION,
    "brands": {
        "michelin": 1,
        "bridgestone": 2,
        "continental": 3,
        "dunlop": 4,
        "pirelli": 5,
        "goodyear": 6,
        "hankook": 7,
        "firestone": 11,
        "fulda": 16,
        "nokian": 44,
        "yokohama": 21,
        "falken": 25,
        "toyo": 37,
        "vredestein": 38,
        "kumho": 39,
        "bf_goodrich": 46,
        "kleber": 47,
        "uniroyal": 40,
        "kumho": 30,
        "marshall": 77,
        "barum": 9,
        "gislaved": 14,
        "sava": 8,
        "semperit": 10,
        "cooper": 54,
        "nexen": 19,
        "maxxis": 78,
        "laufenn": 114,
        "debica": 12,
        "lassa": 24,
        "matador": 13,
        "viking": 55,
        "petlas": 109,
        "kormoran": 48,
        "taurus": 85,
        "radar": 269,
        "sailun": 51,
        "goodride": 64,
        "westlake": 45,
        "zeetex": 52,
        "aplus": 118,
        "atlas": 122,
        "arivo": 297,
        "austone": 415,
        "ceat": 362,
        "dynamo": 342,
        "firemax": 224,
        "fortuna": 198,
        "fronway": 316,
        "gripmax": 110,
        "hifly": 91,
        "imperial": 116,
        "ilink": 389,
        "lanspider": 402,
        "leao": 234,
        "mastersteel": 328,
        "minerva": 43,
        "roadhog": 330,
        "roadx": 386,
        "sunfull": 221,
        "sunny": 60,
        "sunwide": 363,
        "sumitomo": 360,
        "superia": 200,
        "tracmax": 217,
        "trazano": 378,
        "triangle": 69,
        "tristar": 126,
        "tyfoon": 94,
        "windforce": 208,
        "zmax": 341,
        "crosswind": 403,
        "greentrac": 406,
        "kustone": 413,
        "prinx": 414,
        "massimo": 418,
        "atlander": 425,
        "yartu": 432,

    },
    "seasons": {
        "vasarinės": 4,
        # "universalios": 5,
        # "žieminės": 6,
    },
}
