name: Padangos Scraper

on:
  schedule:
    #- cron: "1 8 * * 1-5"   # 10:00 Lietuvos laiku (UTC+2) 1-5 darbo dienomis (1-7)
    #- cron: "1 16 5 * 1-5"  # 18:00 Lietuvos laiku (UTC+2) 5 menesio diena, 1-5 darbo dienomis
    #- cron: "1 8 10 4 1-5"  # 10:00 Lietuvos laiku (UTC+2) 10 menesio diena (1-31),4 mienuo (1-12)
    - cron: "1 8,16 * * *"     # 10:00 ir 18:00 Lietuvos laiku (UTC+2) kasdien, 1-7 dienomis
  workflow_dispatch:        # leidzia paleisti ranka per GitHub UI


concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false  # laukia kol baigsis, nepradeda naujo


jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run scraper
        env:
          SUPABASE_URL_PADANGOS: ${{secrets.SUPABASE_URL_PADANGOS}}
          SUPABASE_API_KEY_PADANGOS: ${{secrets.SUPABASE_API_KEY_PADANGOS}}
        run: |
          uv run python main.py
